using System.Text;
using System.Reflection;
using DumpDetective.Core.Interfaces;
using DumpDetective.Core.Models;
using DumpDetective.Core.Models.CommandData;
using DumpDetective.Core.Utilities;
using DumpDetective.Reporting.Reports;

namespace DumpDetective.Reporting.Sinks;

/// <summary>
/// Modern redesign of the HTML sink — fully offline, no external dependencies.
/// Same features as <see cref="HtmlSink"/> but with a refreshed visual theme:
///   • Indigo-accent color palette with clean slate sidebar
///   • Pill-badge labels on Explain blocks
///   • Tighter card shadows, improved typography
///   • All layout and interaction features preserved
/// </summary>
public sealed class HtmlSink : IRenderSink
{
    readonly StreamWriter _w;
    bool _inSection;
    bool _chapterBodyOpen;
    int  _sectionSeq;
    int  _tableSeq;
    int  _chapterSeq;
    int  _treeSeq;
    int  _chartSeq;

    public bool    IsFile   => true;
    public string? FilePath => (_w.BaseStream as FileStream)?.Name;

    public HtmlSink(string path)
    {
        _w = new StreamWriter(path, append: false, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        WriteDocHeader();
    }

    // ── IRenderSink ───────────────────────────────────────────────────────────

    public void Header(string title, string? subtitle = null, int navLevel = 0, string? commandName = null)
    {
        CloseSection();
        int id = ++_chapterSeq;
        int navLevelOverride = navLevel;
        string meta = string.Empty;
        if (subtitle is not null)
        {
            var parts = subtitle
                .Split('|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(p =>
                {
                    string cls = "chip";
                    if (p.StartsWith("Score:", StringComparison.OrdinalIgnoreCase))
                    {
                        if (p.Contains("/100"))
                        {
                            var numStr = p.Replace("Score:", "").Trim().Split('/')[0].Trim();
                            if (int.TryParse(numStr, out int sc))
                                cls = sc >= 70 ? "chip chip-ok" : sc >= 40 ? "chip chip-warn" : "chip chip-crit";
                        }
                    }
                    return $"<span class=\"{cls}\">{H(p)}</span>";
                });
            meta = $"<div class=\"hero-meta\">{string.Join(string.Empty, parts)}</div>";
        }

        // Inject plugin badge when this report was generated by a third-party plugin.
        string? pluginName = CommandBase.CurrentPluginName;
        if (pluginName is not null)
        {
            string badge = $"<span class=\"chip chip-plugin\" title=\"Third-party plugin: {H(pluginName)}\">⚠ plugin</span>";
            meta = meta.Length > 0
                ? meta[..^6] + badge + "</div>"   // insert before closing </div>
                : $"<div class=\"hero-meta\">{badge}</div>";
        }

        if (_chapterBodyOpen)
            _w.WriteLine("</div> <!-- /chapter-body -->");

        int resolvedLevel;
        if (navLevelOverride > 0)
            resolvedLevel = navLevelOverride;
        else if (CommandBase.SuppressVerbose)
            resolvedLevel = title.StartsWith("Per-Dump Report", StringComparison.OrdinalIgnoreCase) ? 1 : 2;
        else
            resolvedLevel = 1;

        string displayTitle = resolvedLevel >= 2
            ? System.Text.RegularExpressions.Regex.Replace(title, @"^Dump Detective\s*[—\-]\s*", string.Empty, System.Text.RegularExpressions.RegexOptions.IgnoreCase)
            : title;

        // Mark as a nav group divider (collapsible section header) when no commandName and level 2
        string navGroupAttr = (commandName == null && resolvedLevel == 2) ? " data-nav-group=\"1\"" : string.Empty;

        // Stamp the owning CLI command name so other report elements (Correlation
        // Signals, Action Queue, ...) can jump straight to this chapter by name via
        // scrollToCommand('heap-stats') instead of guessing a DOM id.
        string commandAttr = commandName is not null ? $" data-command=\"{H(commandName)}\"" : string.Empty;

                _w.WriteLine($"""
                        <div class="hero nav-track" id="ch{id}" data-nav-level="{resolvedLevel}" data-track-kind="hero"{navGroupAttr}{commandAttr}>
              <h1 class="hero-title">{H(displayTitle)}</h1>
              {meta}
            </div>
            <div class="chapter-body" id="chb{id}">
            """);
        _chapterBodyOpen = true;
    }

    public void Section(string title, string? sectionKey = null)
    {
        CloseSection();
        int id = ++_sectionSeq;
        string tip = sectionKey is not null ? TipHtmlByKey(sectionKey) ?? TipHtml(title) : TipHtml(title);
                _w.WriteLine($"""
                        <div class="card nav-track" id="s{id}" data-track-kind="section">
              <h2 class="card-title" onclick="toggleCard('s{id}')">
                <span class="card-arrow">▾</span>{H(title)}{tip}
              </h2>
              <div class="card-body">
            """);
        _inSection = true;
    }

    static string? TipHtmlByKey(string key)
    {
        foreach (var (k, text) in s_tooltipsByKey)
            if (k.Equals(key, StringComparison.OrdinalIgnoreCase))
            {
                string lines = string.Join("<br>", text.Split('\n'));
                return $""" <span class="tip-wrap" data-tip="{lines}" onmouseenter="showTip(this)" onmouseleave="hideTip()" onclick="event.stopPropagation()"><span class="tip-icon">?</span></span>""";
            }
        return null;
    }

    static string TipHtml(string title)
    {
        foreach (var (key, text) in s_tooltips)
            if (title.Contains(key, StringComparison.OrdinalIgnoreCase))
            {
                string lines = string.Join("<br>", text.Split('\n'));
                return $""" <span class="tip-wrap" data-tip="{lines}" onmouseenter="showTip(this)" onmouseleave="hideTip()" onclick="event.stopPropagation()"><span class="tip-icon">?</span></span>""";
            }
        return string.Empty;
    }

    static readonly (string Key, string Text)[] s_tooltips =
    [
        ("Dump Timeline",           "Temporal ordering of all analyzed dump snapshots.\nUse to correlate symptoms with capture time."),
        ("Incident Summary",        "Health scores and critical findings per snapshot.\nQuickly identifies the most degraded dump."),
        ("Overall Growth Summary",  "Memory, thread, and object count deltas across dumps.\nSteady growth without release indicates a leak."),
        ("Thread & Application",    "Thread pool queue depth and worker saturation.\nHigh pressure indicates starvation or lock contention."),
        ("Event Leak",              "Event handler subscriptions growing across snapshots.\nUnsubscribed handlers keep publisher objects alive."),
        ("Finalize Queue Detail",   "Finalizer queue size trend across snapshots.\nGrowth indicates IDisposable pattern violations."),
        ("Highly Referenced",       "Objects with the most incoming references.\nHigh counts often reveal retention roots."),
        ("Rooted Objects",          "Objects reachable from static or thread roots.\nRooted objects cannot be collected by GC."),
        ("Duplicate String",        "Identical string instances present in the heap.\nConsolidate with string.Intern or a shared dictionary."),
        ("String Duplicate",        "Identical string instances present in the heap.\nConsolidate with string.Intern or a shared dictionary."),
        ("Memory Leak Analysis",    "Types that accumulate across snapshots without release.\nIndicates missing Dispose calls or static retention."),
        ("Diagnosis Summary",       "Cross-snapshot comparison of key health signals.\nHighlights degradation trends and probable root causes."),
        ("Heap Statistics",         "Total managed heap size and per-segment breakdown.\nHigh committed memory may indicate GC pressure."),
        ("GC Generation Summary",   "Object counts by generation (Gen0/Gen1/Gen2/LOH).\nGen2 accumulation is the primary signal of a memory leak."),
        ("Heap Fragmentation",      "Free memory gaps between live objects on the heap.\nHigh fragmentation degrades allocation performance."),
        ("Large Objects",           "Objects over 85,000 bytes on the Large Object Heap.\nLOH is rarely compacted; leaks here cause OutOfMemoryException."),
        ("Exception Analysis",      "Exceptions found on thread stacks or in the heap.\nFrequent exceptions degrade throughput significantly."),
        ("Thread Analysis",         "Thread count, state, and call stacks.\nHigh counts or stuck threads indicate contention or deadlock."),
        ("Thread Pool",             "Managed thread pool workers, queue depth, and completions.\nQueue growth signals async starvation."),
        ("Async State Machine",     "In-flight async/await continuations.\nBacklog growth indicates a downstream bottleneck."),
        ("Deadlock",                "Cycles detected in lock-wait graphs.\nA single deadlock causes a complete application hang."),
        ("Finalizer Queue",         "Objects queued for finalization by the GC.\nGrowth indicates improper IDisposable usage."),
        ("GC Handle Table",         "GC-tracked and pinned object handles.\nExcess pinned handles fragment the managed heap."),
        ("Pinned Objects",          "Objects pinned in memory for native interop or unsafe code.\nExcessive pinning creates heap fragmentation."),
        ("Weak Reference",          "WeakReference objects tracked by the GC.\nExcessive weak refs may indicate problematic caching patterns."),
        ("Static Reference",        "Static fields that hold object references.\nStatic roots prevent GC from collecting referenced objects."),
        ("Timer Leak",              "Timer instances that were created but never disposed.\nLeaking timers keep callbacks and closures alive indefinitely."),
        ("Event Analysis",          "Event handler subscription counts by type.\nGrowth across dumps is a reliable leak indicator."),
        ("WCF Channel",             "Open WCF client channel instances.\nAborted or faulted channels must be explicitly closed."),
        ("DB Connection Pool",      "SQL/database connection pool usage and leaks.\nPool exhaustion causes timeouts and application hangs."),
        ("HTTP",                    "Outgoing HTTP requests and connection instances.\nStuck or leaked requests indicate downstream service issues."),
        ("Module List",             "Loaded .NET assemblies and native modules.\nUnexpected modules may indicate dynamic injection or leaks."),
    ];

    static readonly (string Key, string Text)[] s_tooltipsByKey =
    [
        ("findings",              "Scored health signals detected in this dump.\nCritical findings require immediate investigation."),
        ("memory",                "Managed heap distribution across GC generations.\nGen2 growth is the primary memory leak signal."),
        ("threads",               "Thread state, blocking, and thread pool pressure.\nBlocked threads and empty idle pool indicate contention or starvation."),
        ("async-backlog",         "Suspended async/await state machines.\nHigh counts indicate a downstream bottleneck or thread pool starvation."),
        ("exceptions",            "Exception objects on the heap and active exceptions on threads.\nActive exceptions indicate crash-related conditions."),
        ("leaks-handles",         "Resource handles, finalizer queue, timers, WCF channels, and connections.\nResource leaks can exhaust system limits before memory pressure is visible."),
        ("event-leaks",           "Event handler subscriptions preventing garbage collection.\nSubscriber objects cannot be collected while the publisher holds delegate references."),
        ("string-duplicates",     "Identical string values stored in separate objects.\nDeduplication with string.Intern or shared constants reduces heap pressure."),
        ("memory-leak-analysis",  "Gen2 percentage and type accumulation analysis.\nGen2 > 50% of heap is a strong managed memory leak signal."),
        ("heap-fragmentation",    "Free space between live heap objects.\nHigh fragmentation causes allocation failures and GC compaction overhead."),
        ("finalizer-queue",       "Objects queued for finalization before memory can be reclaimed.\nLarge queues indicate IDisposable pattern violations."),
        ("deadlock-analysis",     "Circular lock-wait cycles detected from Monitor ownership data.\nA single deadlock halts all threads sharing those locks."),
        ("gen-breakdown",         "Memory distribution across GC generations.\nGen2 > 70% of heap causes frequent expensive Gen2 collections."),
    ];

    public void KeyValues(IReadOnlyList<(string Key, string Value)> pairs, string? title = null)
    {
        if (title is not null) _w.WriteLine($"<h3>{H(title)}</h3>");
        _w.WriteLine("<div class=\"kv-grid\">");
        foreach (var (k, v) in pairs)
        {
            string valHtml = H(v);
            if (k.Contains("score", StringComparison.OrdinalIgnoreCase) ||
              k.Contains("health", StringComparison.OrdinalIgnoreCase))
            {
              static string BadgeHtml(string part)
              {
                var numPart = part.Split('/')[0].Trim();
                if (int.TryParse(numPart, out int score))
                {
                  string badgeCls = score >= 70 ? "badge-ok" : score >= 40 ? "badge-warn" : "badge-crit";
                  return $"<span class=\"score-badge {badgeCls}\">{H(part)}</span>";
                }

                return H(part);
              }

              static string RenderScoreTrend(string text)
              {
                int arrowIdx = text.IndexOf(" → ", StringComparison.Ordinal);
                if (arrowIdx < 0)
                  return BadgeHtml(text.Trim());

                string left = text[..arrowIdx].Trim();
                string right = text[(arrowIdx + 3)..].Trim();
                string delta = string.Empty;
                var deltaMatch = System.Text.RegularExpressions.Regex.Match(right, @"^(.*?)(\s*\([^)]+\))\s*$");
                if (deltaMatch.Success)
                {
                  right = deltaMatch.Groups[1].Value.Trim();
                  delta = deltaMatch.Groups[2].Value.Trim();
                }

                string deltaHtml = delta.Length > 0 ? $" <span class=\"kv-delta\">{H(delta)}</span>" : string.Empty;
                return $"{BadgeHtml(left)} <span class=\"kv-arrow\">&rarr;</span> {BadgeHtml(right)}{deltaHtml}";
              }

              int diffSepIdx = v.IndexOf(" ⟹ ", StringComparison.Ordinal);
              if (diffSepIdx < 0)
                diffSepIdx = v.IndexOf("⟹", StringComparison.Ordinal);

              if (diffSepIdx >= 0)
              {
                string left = v[..diffSepIdx].Trim();
                string right = v[(v[diffSepIdx] == '⟹' ? diffSepIdx + 1 : diffSepIdx + 3)..].Trim();
                valHtml = $"{RenderScoreTrend(left)} <span class=\"kv-arrow\">⟹</span> {RenderScoreTrend(right)}";
              }
              else
              {
                valHtml = RenderScoreTrend(v);
              }
            }
            _w.WriteLine($"<div class=\"kv-row\"><span class=\"kv-key\">{H(k)}</span><span class=\"kv-val\">{valHtml}</span></div>");
        }
        _w.WriteLine("</div>");
    }

    public void Gauges(IReadOnlyList<(string Label, double Value, string Unit)> items, double barMax = 100.0)
    {
        _w.WriteLine("<div class=\"gauge-grid\">");
        foreach (var (label, value, unit) in items)
        {
            double pct       = barMax > 0 ? value / barMax * 100.0 : 0;
            double barWidth  = Math.Min(pct, 100.0);
            string levelCls  = pct >= 100 ? "g-crit" : pct >= 80 ? "g-high" : pct >= 50 ? "g-med" : "g-ok";

            _w.Write($"<div class=\"gauge-row {levelCls}\">");
            _w.Write($"<span class=\"gauge-label\">{H(label)}</span>");
            _w.Write($"<div class=\"gauge-track\"><div class=\"gauge-fill\" style=\"width:{barWidth:F1}%\"></div></div>");

            string valStr = value == Math.Floor(value)
                ? $"{value:N0}{H(unit)}"
                : $"{value:F1}{H(unit)}";
            if (pct > 100 && barMax > 0)
            {
                double mult = value / barMax;
                string multStr = mult >= 10 ? $"{mult:N1}" : $"{mult:F2}";
                _w.Write($"<span class=\"gauge-val\">{valStr}<span class=\"gauge-mult\">×{multStr}</span></span>");
            }
            else
            {
                _w.Write($"<span class=\"gauge-val\">{valStr}</span>");
            }
            _w.WriteLine("</div>");
        }
        _w.WriteLine("</div>");
    }

    // ── Chart types ───────────────────────────────────────────────────────────

    private static readonly string[] ChartPalette =
    [
        "#6366f1","#22c55e","#f59e0b","#ef4444","#06b6d4",
        "#8b5cf6","#ec4899","#84cc16","#f97316","#14b8a6",
        "#0ea5e9","#a855f7","#10b981","#f43f5e","#eab308",
    ];

    public void DonutChart(IReadOnlyList<(string Label, double Value)> segments,
                           string? caption = null, string? centerText = null)
    {
        double total = segments.Sum(s => s.Value);
        if (total <= 0) return;

        const double cx = 50, cy = 50, ro = 42, ri = 24;
        double angle = -Math.PI / 2;   // start at 12 o'clock
        var paths  = new System.Text.StringBuilder();
        var legend = new System.Text.StringBuilder();

        for (int i = 0; i < segments.Count; i++)
        {
            var (lbl, val) = segments[i];
            double frac = val / total;
            double sweep = frac >= 0.9999 ? Math.PI * 2 * 0.9999 : frac * Math.PI * 2;
            double endAngle = angle + sweep;
            int large = sweep > Math.PI ? 1 : 0;
            string color = ChartPalette[i % ChartPalette.Length];
            string pct = $"{frac * 100:F1}%";

            double x1 = cx + ro * Math.Cos(angle),  y1 = cy + ro * Math.Sin(angle);
            double x2 = cx + ro * Math.Cos(endAngle), y2 = cy + ro * Math.Sin(endAngle);
            double x3 = cx + ri * Math.Cos(endAngle), y3 = cy + ri * Math.Sin(endAngle);
            double x4 = cx + ri * Math.Cos(angle),  y4 = cy + ri * Math.Sin(angle);

            paths.Append($"""<path data-tip="{H(lbl)}: {pct}" d="M{x1:F2},{y1:F2} A{ro},{ro} 0 {large},1 {x2:F2},{y2:F2} L{x3:F2},{y3:F2} A{ri},{ri} 0 {large},0 {x4:F2},{y4:F2} Z" fill="{color}" class="donut-seg" style="cursor:pointer"/>""");
            legend.Append($"<li class=\"donut-li\"><span class=\"donut-dot\" style=\"background:{color}\"></span><span class=\"donut-lbl\">{H(lbl)}</span><span class=\"donut-pct\">{pct}</span></li>");
            angle = endAngle;
        }

        if (caption is not null) _w.WriteLine($"<p class=\"caption\">{H(caption)}</p>");
        _w.WriteLine("<div class=\"chart-card\"><div class=\"donut-layout\">");
        _w.WriteLine("<svg class=\"donut-svg\" viewBox=\"0 0 100 100\">");
        _w.Write(paths);
        if (centerText is not null)
        {
            var parts = centerText.Split('\n');
            _w.WriteLine($"<text x=\"50\" y=\"{(parts.Length > 1 ? "46" : "52")}\" class=\"donut-ctr-top\">{H(parts[0])}</text>");
            if (parts.Length > 1)
                _w.WriteLine($"<text x=\"50\" y=\"58\" class=\"donut-ctr-bot\">{H(parts[1])}</text>");
        }
        _w.WriteLine("</svg>");
        _w.WriteLine($"<ul class=\"donut-legend\">{legend}</ul>");
        _w.WriteLine("</div></div>");
    }

    public void StackedBar(IReadOnlyList<(string Label, double Value)> segments,
                           string? unit = null, string? caption = null,
                           string? valueMode = null)
    {
        double total = segments.Sum(s => s.Value);
        if (total <= 0) return;

        bool sizeMode = string.Equals(valueMode, "size", StringComparison.Ordinal);

        var track  = new System.Text.StringBuilder();
        var legend = new System.Text.StringBuilder();

        for (int i = 0; i < segments.Count; i++)
        {
            var (lbl, val) = segments[i];
            double pct = val / total * 100;
            string color = ChartPalette[i % ChartPalette.Length];
            string displayVal = sizeMode
                ? DumpDetective.Core.Utilities.DumpHelpers.FormatSize((long)val)
                : $"{val:F1}{H(unit ?? "")}";
            string tip = $"{H(lbl)}: {displayVal} ({pct:F1}%)";
            track.Append($"<div class=\"sbar-seg\" style=\"width:{pct:F2}%;background:{color}\" data-tip=\"{tip}\"></div>");
            legend.Append($"<li class=\"sbar-li\"><span class=\"sbar-dot\" style=\"background:{color}\"></span><span class=\"sbar-lbl\">{H(lbl)}</span><span class=\"sbar-val\">{displayVal}</span><span class=\"sbar-pct\">({pct:F1}%)</span></li>");
        }

        if (caption is not null) _w.WriteLine($"<p class=\"caption\">{H(caption)}</p>");
        _w.WriteLine("<div class=\"chart-card\"><div class=\"sbar-wrap\">");
        _w.WriteLine($"<div class=\"sbar-track\">{track}</div>");
        _w.WriteLine($"<ul class=\"sbar-legend\">{legend}</ul>");
        _w.WriteLine("</div></div>");
    }

    public void Sparkline(IReadOnlyList<double> values, string? caption = null, string? unit = null,
                          string? valueMode = null)
    {
        if (values.Count == 0) return;

        bool sizeMode = string.Equals(valueMode, "size", StringComparison.Ordinal);
        string FormatVal(double v) => sizeMode
            ? DumpDetective.Core.Utilities.DumpHelpers.FormatSize((long)v)
            : $"{v:F1}{H(unit ?? "")}";

        double min = values.Min(), max = values.Max();
        double range = max - min;
        if (range == 0) range = 1;

        const int W = 400, Ht = 36;
        var pts  = new System.Text.StringBuilder();
        var area = new System.Text.StringBuilder();
        area.Append($"M0,{Ht} ");
        for (int i = 0; i < values.Count; i++)
        {
            double x = (double)i / Math.Max(values.Count - 1, 1) * W;
            double y = Ht - (values[i] - min) / range * (Ht - 6) - 3;
            pts.Append($"{x:F1},{y:F1} ");
            area.Append($"L{x:F1},{y:F1} ");
        }
        area.Append($"L{W:F1},{Ht} Z");

        int id = ++_chartSeq;
        const string color = "#6366f1";

        _w.WriteLine("<div class=\"mspark-card\">");
        _w.Write("<div class=\"mspark-series\">");
        if (caption is not null)
            _w.Write($"<span class=\"mspark-lbl\" title=\"{H(caption)}\">{H(caption)}</span>");
        _w.Write("<div class=\"mspark-col\">");
        string dataVals = "[" + string.Join(",", values.Select(v => v.ToString("F2", System.Globalization.CultureInfo.InvariantCulture))) + "]";
        string dataUnit = unit is not null ? $" data-unit=\"{H(unit)}\"" : "";
        string dataSz   = sizeMode ? " data-sizemode=\"1\"" : "";
        _w.Write($"<svg class=\"mspark-svg\" viewBox=\"0 0 {W} {Ht}\" preserveAspectRatio=\"none\" data-vals=\"{dataVals}\"{dataUnit}{dataSz}>");
        _w.Write($"<defs><linearGradient id=\"sg{id}\" x1=\"0\" y1=\"0\" x2=\"0\" y2=\"1\"><stop offset=\"0%\" stop-color=\"{color}\" stop-opacity=\".22\"/><stop offset=\"100%\" stop-color=\"{color}\" stop-opacity=\"0\"/></linearGradient></defs>");
        _w.Write($"<path d=\"{area}\" fill=\"url(#sg{id})\"/>");
        _w.Write($"<polyline points=\"{pts}\" class=\"mspark-line\" style=\"stroke:{color}\"/>");
        _w.Write("<line class=\"spark-xhair\" x1=\"0\" y1=\"0\" x2=\"0\" y2=\"36\" style=\"display:none\"/>");
        _w.Write("<ellipse class=\"spark-dot\" rx=\"3\" ry=\"3\" cx=\"0\" cy=\"0\" style=\"display:none\"/>");
        _w.Write($"<rect class=\"spark-overlay\" x=\"0\" y=\"0\" width=\"{W}\" height=\"{Ht}\" fill=\"transparent\" style=\"cursor:crosshair\"/>");
        _w.Write("</svg>");
        _w.Write($"<span class=\"mspark-stats\">min <b>{FormatVal(min)}</b>&ensp;avg <b>{FormatVal(values.Average())}</b>&ensp;max <b>{FormatVal(max)}</b>&ensp;<span style=\"color:{color};font-weight:700\">&#9632;</span></span>");
        _w.Write("</div>");
        _w.WriteLine("</div>");
        _w.WriteLine("</div>");
    }

    public void MultiSparkline(
        IReadOnlyList<(string Label, IReadOnlyList<double> Values, string? Unit)> series,
        string? caption = null, string? valueMode = null)
    {
        if (series.Count == 0 || series.All(s => s.Values.Count == 0)) return;

        bool sizeMode = string.Equals(valueMode, "size", StringComparison.Ordinal);
        string FormatVal(double v, string? u) => sizeMode
            ? DumpDetective.Core.Utilities.DumpHelpers.FormatSize((long)v)
            : $"{v:F1}{H(u ?? "")}";

        if (caption is not null) _w.WriteLine($"<p class=\"caption\">{H(caption)}</p>");
        _w.WriteLine("<div class=\"mspark-card\">");

        const int W = 400, Ht = 36;
        int baseId = ++_chartSeq;

        for (int si = 0; si < series.Count; si++)
        {
            var (label, values, unit) = series[si];
            if (values.Count == 0) continue;

            string color = ChartPalette[si % ChartPalette.Length];
            double min   = values.Min();
            double max   = values.Max();
            double range = max - min;
            if (range == 0) range = 1;

            var pts  = new System.Text.StringBuilder();
            var area = new System.Text.StringBuilder();
            area.Append($"M0,{Ht} ");
            for (int i = 0; i < values.Count; i++)
            {
                double x = (double)i / Math.Max(values.Count - 1, 1) * W;
                double y = Ht - (values[i] - min) / range * (Ht - 6) - 3;
                pts.Append($"{x:F1},{y:F1} ");
                area.Append($"L{x:F1},{y:F1} ");
            }
            area.Append($"L{W:F1},{Ht} Z");

            int sid = baseId * 100 + si;
            _w.Write("<div class=\"mspark-series\">");
            _w.Write($"<span class=\"mspark-lbl\" title=\"{H(label)}\">{H(label)}</span>");
            _w.Write("<div class=\"mspark-col\">");
            string dvVals = "[" + string.Join(",", values.Select(v => v.ToString("F2", System.Globalization.CultureInfo.InvariantCulture))) + "]";
            string dvUnit = unit is not null ? $" data-unit=\"{H(unit)}\"" : "";
            string dvSz   = sizeMode ? " data-sizemode=\"1\"" : "";
            string dvCol  = $" data-color=\"{color}\"";
            _w.Write($"<svg class=\"mspark-svg\" viewBox=\"0 0 {W} {Ht}\" preserveAspectRatio=\"none\" data-vals=\"{dvVals}\"{dvUnit}{dvSz}{dvCol}>");
            _w.Write($"<defs><linearGradient id=\"msg{sid}\" x1=\"0\" y1=\"0\" x2=\"0\" y2=\"1\"><stop offset=\"0%\" stop-color=\"{color}\" stop-opacity=\".22\"/><stop offset=\"100%\" stop-color=\"{color}\" stop-opacity=\"0\"/></linearGradient></defs>");
            _w.Write($"<path d=\"{area}\" fill=\"url(#msg{sid})\"/>");
            _w.Write($"<polyline points=\"{pts}\" class=\"mspark-line\" style=\"stroke:{color}\"/>");
            _w.Write("<line class=\"spark-xhair\" x1=\"0\" y1=\"0\" x2=\"0\" y2=\"36\" style=\"display:none\"/>");
            _w.Write("<ellipse class=\"spark-dot\" rx=\"3\" ry=\"3\" cx=\"0\" cy=\"0\" style=\"display:none\"/>");
            _w.Write($"<rect class=\"spark-overlay\" x=\"0\" y=\"0\" width=\"{W}\" height=\"{Ht}\" fill=\"transparent\" style=\"cursor:crosshair\"/>");
            _w.Write("</svg>");
            _w.Write($"<span class=\"mspark-stats\">min <b>{FormatVal(min, unit)}</b>&ensp;avg <b>{FormatVal(values.Average(), unit)}</b>&ensp;max <b>{FormatVal(max, unit)}</b>&ensp;<span style=\"color:{color};font-weight:700\">&#9632;</span></span>");
            _w.Write("</div>");
            _w.WriteLine("</div>");
        }
        _w.WriteLine("</div>");
    }

    public void CompareBar(
        IReadOnlyList<(string Label, double ValueA, double ValueB)> items,
        string? labelA = null, string? labelB = null,
        string? unit = null, string? caption = null, string? valueMode = null)
    {
        if (items.Count == 0) return;

        bool sizeMode = string.Equals(valueMode, "size", StringComparison.Ordinal);
        string FormatVal(double v) => sizeMode
            ? DumpDetective.Core.Utilities.DumpHelpers.FormatSize((long)v)
            : $"{v:F1}{H(unit ?? "")}";

        double globalMax = items.Max(i => Math.Max(i.ValueA, i.ValueB));
        if (globalMax <= 0) return;

        const string ColorA = "#6366f1";
        const string ColorB = "#22c55e";
        string lblA = labelA ?? "A";
        string lblB = labelB ?? "B";

        if (caption is not null) _w.WriteLine($"<p class=\"caption\">{H(caption)}</p>");
        _w.WriteLine("<div class=\"chart-card cbar-card\">");

        _w.Write("<div class=\"cbar-header\">");
        _w.Write("<span></span>");
        _w.Write("<div class=\"cbar-legend\">");
        _w.Write($"<span class=\"cbar-legend-item\"><span class=\"cbar-legend-dot\" style=\"background:{ColorA}\"></span>{H(lblA)}</span>");
        _w.Write($"<span class=\"cbar-legend-item\"><span class=\"cbar-legend-dot\" style=\"background:{ColorB}\"></span>{H(lblB)}</span>");
        _w.Write("</div>");
        _w.WriteLine("</div>");

        foreach (var (label, valA, valB) in items)
        {
            double pctA = Math.Min(valA / globalMax * 100.0, 100.0);
            double pctB = Math.Min(valB / globalMax * 100.0, 100.0);
            bool   both = valA > 0 && valB > 0;

            _w.Write($"<div class=\"cbar-row{(both ? " cbar-row-match" : "")}\">");
            _w.Write($"<span class=\"cbar-lbl\" title=\"{H(label)}\">{H(label)}</span>");
            _w.Write("<div class=\"cbar-bars\">");
            _w.Write($"<div class=\"cbar-bar-row\" data-tip=\"{H(label)} — {H(lblA)}: {H(FormatVal(valA))}\"><div class=\"cbar-bar-track\"><div class=\"cbar-a\" style=\"width:{pctA:F1}%\"></div></div><span class=\"cbar-bar-val\">{H(FormatVal(valA))}</span></div>");
            _w.Write($"<div class=\"cbar-bar-row\" data-tip=\"{H(label)} — {H(lblB)}: {H(FormatVal(valB))}\"><div class=\"cbar-bar-track\"><div class=\"cbar-b\" style=\"width:{pctB:F1}%\"></div></div><span class=\"cbar-bar-val\">{H(FormatVal(valB))}</span></div>");
            _w.Write("</div>");
            _w.WriteLine("</div>");
        }
        _w.WriteLine("</div>");
    }

    public void Table(string[] headers, IReadOnlyList<string[]> rows, string? caption = null)
    {
        int tid = ++_tableSeq;
        bool large = rows.Count > 50;

        // A column literally named "Jump" holding a CLI command name (e.g. "heap-stats")
        // renders as a one-click scroll-to-evidence button instead of plain text. Other
        // sinks (Markdown/Text/JSON/...) just print the command name — this is additive,
        // not a format change, so no IRenderSink signature change was needed for it.
        int jumpCol = Array.IndexOf(headers, "Jump");

        if (caption is not null) _w.WriteLine($"<p class=\"caption\">{H(caption)}</p>");

        _w.WriteLine($"""
            <div class="table-toolbar">
              <input class="tbl-search" id="ts{tid}" placeholder="Filter rows…" oninput="filterTable({tid})" autocomplete="off">
              <span class="row-count" id="rc{tid}">{rows.Count:N0} rows</span>
              <button class="tbl-csv-btn" onclick="exportCsv({tid})" title="Export visible rows as CSV">⬇ CSV</button>
            </div>
            """);

        _w.WriteLine($"<div class=\"table-wrap{(large ? " tbl-large" : "")}\" id=\"tw{tid}\">");
        _w.WriteLine($"<table id=\"t{tid}\" class=\"data-table\">");
        _w.WriteLine("<thead><tr>");
        for (int i = 0; i < headers.Length; i++)
            _w.Write($"<th onclick=\"sortTable({tid},{i})\" title=\"Sort by {H(headers[i])}\">{H(headers[i])}<span class=\"sort-icon\">⇅</span></th>");
        _w.WriteLine("</tr></thead>");
        _w.WriteLine("<tbody>");

        for (int r = 0; r < rows.Count; r++)
        {
            var row = rows[r];
            _w.Write("<tr>");
            for (int i = 0; i < headers.Length; i++)
            {
                string cell = i < row.Length ? row[i] : string.Empty;
                string cellCls = "";
                string cellContent = H(cell);
                if (i == jumpCol && cell.Length > 0 && cell != "—")
                {
                    cellCls = " class=\"tbl-jump\"";
                    cellContent = $"<button class=\"tbl-jump-btn\" onclick=\"scrollToCommand('{cell}')\" title=\"Jump to {H(cell)} evidence\">→ {H(cell)}</button>";
                }
                else if (cell is "↑↑" or "↑↑ ↑↑") cellCls = " class=\"trend-up2\"";
                else if (cell is "↑" or "↑ ↑")  cellCls = " class=\"trend-up\"";
                else if (cell.StartsWith("↓"))    cellCls = " class=\"trend-dn\"";
                else if (cell is "Critical")      { cellCls = " class=\"sev-crit\""; cellContent = "<span class=\"sev-badge sev-badge-crit\">✗ Critical</span>"; }
                else if (cell is "Warning")       { cellCls = " class=\"sev-warn\""; cellContent = "<span class=\"sev-badge sev-badge-warn\">⚠ Warning</span>"; }
                else if (cell is "Info")          { cellCls = " class=\"sev-info\""; cellContent = "<span class=\"sev-badge sev-badge-info\">ℹ Info</span>"; }
                else if (IsMethodCell(cell))      cellCls = " class=\"method-text\"";
                else if (cell.Length > 55)        cellCls = " class=\"long-text\"";
                _w.Write($"<td{cellCls}>{cellContent}</td>");
            }
            _w.WriteLine("</tr>");
        }

        _w.WriteLine("</tbody></table></div>");
    }

    public void Alert(AlertLevel level, string title, string? detail = null, string? advice = null)
    {
        string cls  = level switch { AlertLevel.Critical => "alert-crit", AlertLevel.Warning => "alert-warn", _ => "alert-info" };
        string icon = level switch { AlertLevel.Critical => "✗", AlertLevel.Warning => "⚠", _ => "ℹ" };
        _w.Write($"<div class=\"alert {cls}\"><div class=\"alert-title\"><span class=\"alert-icon\">{icon}</span>{H(title)}</div>");
        if (detail is not null) _w.Write($"<div class=\"alert-detail\">{H(detail)}</div>");
        if (advice  is not null) _w.Write($"<div class=\"alert-advice\"><span class=\"advice-label\">💡 Recommendation</span>{H(advice)}</div>");
        _w.WriteLine("</div>");
    }

    public void Text(string line)  => _w.WriteLine($"<p class=\"body-text\">{H(line)}</p>");
    public void BlankLine()        => _w.WriteLine("<div class=\"spacer\"></div>");
    public void Reference(string label, string url)
        => _w.WriteLine($"<p class=\"ref-link\">📖 {H(label)} <a href=\"{H(url)}\" target=\"_blank\" rel=\"noopener noreferrer\">{H(url)}</a></p>");

    public void BeginDetails(string title, bool open = false)
    {
        string openAttr = open ? " open" : string.Empty;
        _w.WriteLine($"<details{openAttr}><summary class=\"det-sum\">{H(title)}</summary><div class=\"details-body\">");
    }

    public void EndDetails() => _w.WriteLine("</div></details>");

    public void Explain(string? what, string? why = null, string[]? bullets = null,
                        string? impact = null, string? action = null)
    {
        // Rendered as a collapsed accordion in V2 — keeps reports clean;
        // click "About this section" to expand inline help.
        _w.WriteLine("<details class=\"explain-accordion\"><summary class=\"explain-summary\"><span class=\"explain-summary-icon\">ℹ</span>About this section</summary>");
        _w.WriteLine("<div class=\"explain-body\">");
        if (what is not null)
        {
            _w.WriteLine("<div class=\"explain-item\">");
            _w.WriteLine("<span class=\"explain-label\">What this means</span>");
            _w.WriteLine($"<p class=\"explain-text\">{H(what)}</p>");
            _w.WriteLine("</div>");
        }
        if (why is not null)
        {
            _w.WriteLine("<div class=\"explain-item\">");
            _w.WriteLine("<span class=\"explain-label\">Why it matters</span>");
            _w.WriteLine($"<p class=\"explain-text\">{H(why)}</p>");
            _w.WriteLine("</div>");
        }
        if (impact is not null)
        {
            _w.WriteLine("<div class=\"explain-item\">");
            _w.WriteLine("<span class=\"explain-label\">Potential impact</span>");
            _w.WriteLine($"<p class=\"explain-text\">{H(impact)}</p>");
            _w.WriteLine("</div>");
        }
        if (bullets is { Length: > 0 })
        {
            _w.WriteLine("<div class=\"explain-item\">");
            _w.WriteLine("<span class=\"explain-label\">What to look for</span>");
            _w.WriteLine("<ul class=\"explain-bullets\">");
            foreach (var b in bullets) _w.WriteLine($"<li>{H(b)}</li>");
            _w.WriteLine("</ul>");
            _w.WriteLine("</div>");
        }
        if (action is not null)
        {
            _w.WriteLine("<div class=\"explain-item explain-action\">");
            _w.WriteLine("<span class=\"explain-label\">Recommended action</span>");
            _w.WriteLine($"<p class=\"explain-text\">{H(action)}</p>");
            _w.WriteLine("</div>");
        }
        _w.WriteLine("</div></details>");
    }

    public void CallTree(IReadOnlyList<CallTreeNode> roots, string? caption = null, int topN = 20)
    {
        if (roots is null || roots.Count == 0) return;

        // Unique ID so multiple trees on the same page don't clash.
        var treeId = $"ctree{System.Threading.Interlocked.Increment(ref _treeSeq)}";

        if (caption is not null)
            _w.WriteLine($"<p class=\"caption\">{H(caption)}</p>");

        // Expand / Collapse All toolbar for this tree
        _w.WriteLine($"<div class=\"ctree-toolbar\">");
        _w.WriteLine($"  <button class=\"ct-expbtn\" onclick=\"ctExpandAll('{treeId}')\">⊞ Expand All</button>");
        _w.WriteLine($"  <button class=\"ct-expbtn\" onclick=\"ctCollapseAll('{treeId}')\">⊟ Collapse All</button>");
        _w.WriteLine("</div>");

        _w.WriteLine($"<div class=\"ctree-wrap\" id=\"{treeId}\">");
        _w.WriteLine("<table class=\"ctree-table\"><thead><tr>");
        _w.WriteLine("<th class=\"ctw-name\">Method / Module</th>");
        _w.WriteLine("<th class=\"ctw-bar\">Incl %</th>");
        _w.WriteLine("<th class=\"ctw-pct\">Incl %</th>");
        _w.WriteLine("<th class=\"ctw-pct\">Excl %</th>");
        _w.WriteLine("<th class=\"ctw-cnt\">Incl</th>");
        _w.WriteLine("<th class=\"ctw-cnt\">Excl</th>");
        _w.WriteLine("</tr></thead><tbody>");

        // topN limits the number of ROOT nodes shown; children are always fully rendered
        // (they start collapsed, so depth doesn't inflate visible rows).
        int rootsShown = 0;
        foreach (var node in roots)
        {
            if (rootsShown >= topN) break;
            rootsShown++;
            RenderTreeRow(node, 0);
        }
        _w.WriteLine("</tbody></table></div>");
    }

    private void RenderTreeRow(CallTreeNode node, int depth)
    {
        bool hasChildren = node.Children is { Count: > 0 };
        string toggleId  = hasChildren ? $"ct{System.Threading.Interlocked.Increment(ref _treeSeq)}" : string.Empty;
        string indent     = depth > 0 ? $"style=\"padding-left:{8 + depth * 18}px\"" : string.Empty;

        // Heat colour: 0–5% → neutral, 5–20% → orange, >20% → red (light/dark aware via CSS vars)
        string heatClass  = node.InclusivePct >= 20 ? "ct-hot2"
                          : node.InclusivePct >= 5  ? "ct-hot1"
                          : "ct-cool";

        // Bar width capped at 100 px (100% = full bar)
        int barPx = (int)Math.Min(node.InclusivePct, 100);

        string trClick = hasChildren
            ? $" onclick=\"ctToggle('{toggleId}',this.querySelector('.ct-toggle'))\""
            : string.Empty;
        string trClass = hasChildren ? $"ctrow {heatClass} ct-clickable" : $"ctrow {heatClass}";
        _w.Write($"<tr class=\"{trClass}\"{trClick}>");

        // Name cell — contains indent spacer, optional toggle chevron, method+module
        _w.Write("<td class=\"ctw-name\" " + indent + ">");
        if (hasChildren)
            _w.Write($"<span class=\"ct-toggle\">▶</span> ");
        else
            _w.Write("<span class=\"ct-leaf\">·</span> ");
        var _cleanMethod = TraceReportHelpers.CleanIlMethod(node.Method);
        _w.Write($"<span class=\"ct-method\" title=\"{H(_cleanMethod)}\">{H(TruncateName(_cleanMethod, 55))}</span>");
        if (node.Module.Length > 0)
            _w.Write($" <span class=\"ct-mod\">{H(TruncateName(node.Module, 30))}</span>");
        _w.WriteLine("</td>");

        // Bar cell
        _w.WriteLine($"<td class=\"ctw-bar\"><div class=\"ct-bar-bg\"><div class=\"ct-bar\" style=\"width:{barPx}%\"></div></div></td>");

        _w.WriteLine($"<td class=\"ctw-pct\">{node.InclusivePct:F1}%</td>");
        _w.WriteLine($"<td class=\"ctw-pct\">{node.ExclusivePct:F1}%</td>");
        _w.WriteLine($"<td class=\"ctw-cnt\">{node.InclusiveSamples:N0}</td>");
        _w.WriteLine($"<td class=\"ctw-cnt\">{node.ExclusiveSamples:N0}</td>");
        _w.WriteLine("</tr>");

        if (hasChildren)
        {
            _w.WriteLine($"<tr id=\"{toggleId}\" class=\"ct-children\" style=\"display:none\"><td colspan=\"6\" style=\"padding:0\">");
            _w.WriteLine("<table class=\"ctree-table ctree-nested\"><tbody>");
            foreach (var child in node.Children)
                RenderTreeRow(child, depth + 1);
            _w.WriteLine("</tbody></table></td></tr>");
        }
    }

    static string TruncateName(string s, int max) =>
        s.Length <= max ? s : s[..(max - 1)] + "…";

    public void Dispose()
    {
        CloseSection();
        if (_chapterBodyOpen)
            _w.WriteLine("</div> <!-- /chapter-body -->");
        _w.WriteLine(s_footer);
        _w.Dispose();
    }

    // ── Internals ─────────────────────────────────────────────────────────────

    void CloseSection()
    {
        if (_inSection)
        {
            _w.WriteLine("</div></div>");
            _inSection = false;
        }
    }

    /// <summary>
    /// Returns true when the cell looks like a method/type name or a chain of them.
    /// Such cells use word-break:break-all so they wrap at symbol boundaries.
    /// </summary>
    static bool IsMethodCell(string cell)
    {
        if (cell.Length < 30) return false;
        // Chain cells use → separator
        if (cell.Contains('→')) return true;
        // Method cells contain both a dot and a parenthesis (e.g. Namespace.Class.Method(args))
        return cell.Contains('.') && cell.Contains('(');
    }

    static string H(string s) =>
        s.Replace("&", "&amp;")
         .Replace("<", "&lt;")
         .Replace(">", "&gt;")
         .Replace("\"", "&quot;");

    void WriteDocHeader()
    {
        var now = DateTime.Now;
        _w.Write(s_docHeader
            .Replace("{APP_VERSION}", DumpDetective.Core.Utilities.AppInfo.Version)
            .Replace("{GEN_DATE}", now.ToString("yyyy-MM-dd"))
            .Replace("{GEN_TIME}", now.ToString("HH:mm:ss"))
            .Replace("{GEN_DATETIME}", now.ToString("yyyy-MM-dd HH:mm:ss")));
    }

    // ── Template strings (loaded from embedded resources at startup) ─────────

    static readonly string s_docHeader;
    static readonly string s_footer;

    static HtmlSink()
    {
        var asm    = typeof(HtmlSink).Assembly;
        var layout = ReadResource(asm, "HtmlSink.layout.html");
        var css    = ReadResource(asm, "HtmlSink.css");
        var js     = ReadResource(asm, "HtmlSink.js");

        var full  = layout.Replace("{STYLES}", css).Replace("{SCRIPTS}", js);
        const string split = "{DOC_SPLIT}";
        int idx   = full.IndexOf(split, StringComparison.Ordinal);
        s_docHeader = full[..idx];
        s_footer    = full[(idx + split.Length)..];
    }

    static string ReadResource(Assembly asm, string name)
    {
        using var stream = asm.GetManifestResourceStream(name)
            ?? throw new InvalidOperationException($"Missing embedded resource: {name}");
        using var reader = new System.IO.StreamReader(stream);
        return reader.ReadToEnd();
    }
}